feat(FEC-9236): Add support for new live Alpha in cast SDK
kaltura/playkit-js-cast-receiver pull request #42
Opened 2021-04-19 14:24 UTC by dan-ziv

### Description of the Changes

* Remove disable of SEEK operation when playing live.
* Report media status on live-dvr when receiver is in pause state to allow sender refresh his live tag.
* Handle error when trying to set off track as the initial track.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-04-19 18:57 UTC, yairans requested changes

2021-04-19 18:57 UTC, yairans commented on src/receiver-manager.js
>          if (mediaStatus.media) {
```suggestion
        if (this._player.isLive() && mediaStatus.media) {
```

2021-04-19 19:02 UTC, yairans requested changes

2021-04-19 19:02 UTC, yairans commented on src/receiver-manager.js
> +      this._broadcastStatusIntervalId = setInterval(() => {
clear on reset/destroy

2021-04-20 08:37 UTC, dan-ziv commented on src/receiver-manager.js
> +      this._broadcastStatusIntervalId = setInterval(() => {
done

2021-04-20 10:49 UTC, yairans approved these changes

2021-04-20 11:14 UTC, merged